### ISSUE TITLE
Common Language Runtime detected an invalid program

### ISSUE THREAD

**Issue by sinanakyazici** [salarcode/Bois#10]
I'm getting an error like below,

Exception type: System.InvalidProgramException
Message       : Common Language Runtime detected an invalid program.
Stacktrace:
   at Computed_CloudTimeSeriesData_Reader_2114922277(BinaryReader reader, Encoding encoding)
   at Computed_List`1_Reader_318810521(BinaryReader reader, Encoding encoding)
   at Salar.Bois.Types.BoisComputedTypeInfo.InvokeReader[T](BinaryReader reader, Encoding encoding)
   at Salar.Bois.BoisSerializer.Deserialize[T](Stream objectData)

I'm using async programming. It throws this error when multiple Deserialize works together at the same time.

**Comment by salarcode** [comment]
Hi can you provide sample class you serialize?

**Comment by sinanakyazici** [comment]
This class: 

    public class CloudTimeSeriesData
    {
        public long BDIntCode { get; set; }
        public double BDDataValue { get; set; }
    }

**Comment by sinanakyazici** [comment]
I'm using latest unreleased version. Version is 3.0.0.

**Comment by sinanakyazici** [comment]
I created little application. I'm getting 3 different exception. 

- Method 'Computed_TimeSeriesData_Writer_1666539500' does not have a method body.
- Object reference not set to an instance of an object.
- Common Language Runtime detected an invalid program.

`using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace Salar.Bois.NetFx.Test.App
{
    class Program
    {
        static void Main(string[] args)
        {
            var data = CreateTimeSeriesDataObject(1000).ToList();

            Parallel.For(0, 10, i =>
            {
                MemoryStreamTest(data);
            });


        }

        private static void MemoryStreamTest(List<TimeSeriesData> data)
        {
            var TestStream = new MemoryStream();
            var BoisSerializer = new BoisSerializer();
            var sw = new Stopwatch();
            sw.Start();

            BoisSerializer.Serialize(data, TestStream);
            sw.Stop();

            Console.WriteLine("MemoryStream Serialize Time : " + sw.ElapsedMilliseconds + " ms");

            TestStream.Dispose();

            var ms = new MemoryStream(TestStream.ToArray());

            sw.Restart();
            var timeSeriesDatas = BoisSerializer.Deserialize<List<TimeSeriesData>>(ms);

            sw.Stop();

            Console.WriteLine("MemoryStream Deserialize Time : " + sw.ElapsedMilliseconds + " ms");
        }



        private static IEnumerable<TimeSeriesData> CreateTimeSeriesDataObject(long count)
        {
            var c = (int)Math.Sqrt(count);
            var r = new Random();
            var list = new List<TimeSeriesData>();

            var bdIntCode = 1;
            while (list.Count < count)
            {
                var t = new TimeSeriesData { BDIntCode = bdIntCode++, BDDataValue = r.Next(0, 1000) };
                list.Add(t);
            }


            Console.WriteLine($"Created list. Count : {list.Count}");
            return list;
        }
    }

    public class TimeSeriesData
    {
        public long BDIntCode { get; set; }
        public double BDDataValue { get; set; }
    }
}
`

**Comment by salarcode** [comment]
Thank you, I'll investigate it and release the patch for it.

**Comment by sinanakyazici** [comment]
I'm trying to find something for this bug. I couldn't find anything. But I have obtained some assumptions. I think that this bug is about cache system. I fixed code like below and I don't get exception anymore. I know this is not solution. I wanted to share with you to give ideas. 


try
{
    computedType.InvokeWriter(writer, obj, Encoding);
}
catch 
{
    BoisTypeCache.ClearCache();
    computedType = BoisTypeCache.GetRootTypeComputed(type, false, true);
    computedType.InvokeWriter(writer, obj, Encoding);
}

try
{
    return computedType.InvokeReader<T>(reader, Encoding);

}
catch
{
    BoisTypeCache.ClearCache();
    computedType = BoisTypeCache.GetRootTypeComputed(type, true, false);
    return computedType.InvokeReader<T>(reader, Encoding);
}

**Comment by salarcode** [comment]
I think the problem is that BoisTypeCache is not working correctly in multi thread scenario.
It works fine in single thread.
Thank you for reporting.

**Comment by salarcode** [comment]
Fix released
