### ISSUE TITLE
Constructor on type 'SchemaSet' not found.

### ISSUE THREAD

**Issue by ershadnozari** [salarcode/Bois#12]
I'm getting a "Constructor on type 'SchemaSet' not found." error on deserialization. 

```
BinaryReader binaryReader = new BinaryReader(inStream);
Salar.Bois.BoisSerializer s = new Salar.Bois.BoisSerializer();
return s.Deserialize<SchemaSet>(binaryReader.BaseStream);
```

SchemaSet is an interface with two concrete implementation.

**Comment by salarcode** [comment]
Interfaces are not supported.
Can you paste your sample class here?

**Comment by ershadnozari** [comment]
My sample class is fairly complex with other nested interfaces.

**Comment by salarcode** [comment]
Anything like this won't work
```
class Sample{
public ISampleInterface Prop{get;set;}
}
```

As I said interfaces are not supported because the deserializer doesn't know what implementation is used.

**Comment by ershadnozari** [comment]
I’m in a process of migrating away from BinaryFormatter and evaluating different serializers. Serialization/Deserialization of the SchemaSet interface, and other interfaces, works fine using BinaryFormatter.

**Comment by salarcode** [comment]
BinaryFormatter stores that information and that is why the payload size is so big.

**Comment by ershadnozari** [comment]
Ok thanks. Is there any other option to swap out the BinaryFormatter without major  modification to our current code base?
