### ISSUE TITLE
polymorphic objects

### ISSUE THREAD

**Issue by fredrikdaveus** [salarcode/Bois#13]
Hi, can't find any info on if inheritance is supported? The readme says that interfaces are supported though.

class A 
{ 
public A() { }
}
class B : A 
{ 
public B() { }
int PropertyB {get;set;}
}

var A = new B();

Serializing A seems to fail to store the value of PropertyB.

Is this the intended behavior or do I need to adjust the code in any way?

**Comment by salarcode** [comment]
It has nothing to do with polymorphic objects. PropertyB should be public.
