### ISSUE TITLE
Bois doesn't support object parameters?

### ISSUE THREAD

**Issue by ignusfast** [salarcode/Bois#15]
I was hoping to use Bois as a generic serializer in the same way I'm able to use the BinaryFormatter.  Hand any class to a generic serialization/deserialization routine that casts it as an object.  But doing the following in ToBois appears to always return a null byte[]

		private static readonly BoisSerializer Serializer = new BoisSerializer();
		public static byte[] ToBois(this object obj) {
			using (var ms = new MemoryStream()) {
				Serializer.Serialize(obj, ms);
				return ms.ToArray();
			}
		}
		public static object FromBois(this byte[] bytes) {
			return Serializer.Deserialize<object>(new MemoryStream(bytes));
		}

Is this not a valid use-case?  I was hoping to use it in a communication class, which doesn't care what the object being handed to it is.  It just serializes it for transfer.  On the other end, it should deserialize to object, then infer the sent class and handle it accordingly...

**Comment by salarcode** [comment]
The reason why BinaryFormatter can serialize/deserialze the "object" is the same reason it is slow and produces big files.
Use generics like this it should be just fine:
byte[] ToBois<T>(this T obj)

```
private static readonly BoisSerializer Serializer = new BoisSerializer();
public static byte[] ToBois<T>(this T obj) {
	using (var ms = new MemoryStream()) {
		Serializer.Serialize(obj, ms);
		return ms.ToArray();
	}
}
public static T FromBois<T>(this byte[] bytes) {
	return Serializer.Deserialize<T>(new MemoryStream(bytes));
}
```

**Comment by ignusfast** [comment]
Too bad.  Unfortunately, I'm stuck with BinaryFormatter, then.  Not only does Bois not work with a class cast as an object, but it won't serialize any child members of a generic class if they're stored as objects.

Does it really kill performance/output size to reflect an object's type?

**Comment by salarcode** [comment]
Yes it does kill performance/size. The performance come from planned deserialization. With dynamic objects can't do that.
You may find other binary serializers able to retain the object type in the process.
