### ISSUE TITLE
Another deserialization example?

### ISSUE THREAD

**Issue by d-vyd** [salarcode/Bois#16]
I'm relatively new to c#. Your serializer example was clear to me and this works in my code:

```
                    var boisSerializer = new BoisSerializer();
                    using (var file = new FileStream(path, FileMode.Create))
                    {
                        boisSerializer.Serialize(myobject, file);
                    }
```

I don't understand the `datastream` in your deserializer example though. Do I need to open the file and then call Bois? Is there an approach that mirrors the code above?

**Comment by salarcode** [comment]
Where is this `datastream ` you're talking about? Are you talking about deserializing?

**Comment by d-vyd** [comment]
Yes, exactly. I understand the serialization example but not the deserialization example.  
EDIT: I think I got it working. I just hand the deserializer an open file handle?
