### ISSUE TITLE
How does Salar Bois compare to Protobuf?

### ISSUE THREAD

**Issue by azrinsani** [salarcode/Bois#19]
Hi Salar, this is not an issue, I just want to know how Salar Bois compares with protobuf. I am looking for a fast serializer to ensure fast initial data loading of a Xamarin App. All other "faster" serializers fail as while they are faster, they take a hell of a time to initialize. 

PROTOBUF seems to be an option for me due to its fast initialization time. Though i wonder how Salar Bois compares to it. Thanks!

**Comment by salarcode** [comment]
Being fast comes at a cost same as being compact has a cost too. Bois takes the middle ground here while being fast it is also compact. Virtually Bois doesn't need initialization but still can benefit from it. Anyway I would choose Bois anytime.
The other factor you want to consider is the development of the component and how it is supported. Truth to be told, even tough I work on this component sometimes it still is not my priority as I have limited free time. This might be an important factor for you.
