### ISSUE TITLE
Request for supporting netstandard2.0

### ISSUE THREAD

**Issue by dosh1974** [salarcode/Bois#20]
In the process of porting from .NET framework to .NET standard and the decision have been made to use netstandrad2.0.

In .NET framework Bois worked fine, but since the nuget only have netstandard2.1, we can't use it anymore.

Is there a specific reason for going with 2.1 or would it be possible to get a 2.0 version?

Seeing that 2.0 works for more targets:
https://docs.microsoft.com/en-us/dotnet/standard/net-standard

**Comment by salarcode** [comment]
Unfortunately that is not possible. Bois is using some code generators that are only available in netstandard2.1
https://docs.microsoft.com/en-us/dotnet/api/system.reflection.emit.ilgenerator?view=net-6.0#applies-to
