### ISSUE TITLE
Adding a support (de/serialization) for others language

### ISSUE THREAD

**Issue by Dypso** [salarcode/Bois#22]
Bois for c# and specially with LZ4 is absolutely stunning. I will be very interested to use it in order to marshall structure of data between c# process and native process (kind of ipc). But for this I hardly need support to deserialization with C/C++ language.
A library just like [mpack](https://github.com/ludocode/mpack) for messagePack format. 
Is it a possible evolution for your library ? Adding an extention for C/C++ language ?

**Comment by salarcode** [comment]
Happy to see it is helpful.
Unfortunately I have very limited knowledge on C/C++ and even if I did know it well enough, I don't have the time to write such a thing.
