### ISSUE TITLE
Variable output depending on the runtime version used

### ISSUE THREAD

**Issue by Dypso** [salarcode/Bois#23]
I am doing some test serializing an object from a client application build in .Net Core 6 framework and calling a server application running in .Net Framework 4.8 and Ihave observed that the same object is not serialized in the same manner under the two frameworks.
Is that a normal behavior ? Do we need to always serialize and deserialize with the same .Net framework or core version ?
Anoter point, is that my client application is a 64bit process while the server application is a 32 bit process : may be the issue is more related to this point...

**Comment by Dypso** [comment]
After doing some more test, I have found that the problem is effectively come from the using of twodifferent runtimes : if we serialize from a process in .Net Core 6 , we would not deserialize from a process targeting the 4.8 Framework .Net runtime...

**Comment by salarcode** [comment]
Sorry for the late reply, I'm a little busy.
The binary is compatible with different version of .Net runtimes.
Can you provide an example of this incompatibility? A working dto class that has this issue.

**Comment by salarcode** [comment]
I have tested this and the output is same for the same model class

**Comment by Dypso** [comment]
Yes sorry, I have done some more tests and it appears that the error was all mine. My bad. Really sorry.
