### ISSUE TITLE
Note on Behaviour with .NET 6.0

### ISSUE THREAD

**Issue by mousetrap-systems** [salarcode/Bois#24]
I love your serialization library - it provides the storage I need, at speed, without the fluff and guff of other libraries.
Got it working with .NET 6.0 but noticed a behaviour - the following line is essential prior to using the Serialize() method

`BoisSerializer.Initialize<MyCustomClass>();`

As far as I could trace the source code, if this statement is not used then it cannot find the type in BoisTypeCache, and then var computedType = BoisTypeCache.GetRootTypeComputed(type, false, true); returns EnBasicKnownType.Unknown and from there it doesn't know what writer to invoke and the resultant stream is zero bytes.  I had consistent behaviour with even primitives and basic objects like List<string>.

I couldn't figure out why and I don't know enough about how DOTNETCORE internals are evolving .. to work out how to fix it but I was relieved to have it working by using the Initialize method.  It's not an issue so much as just creating a trail for anyone else who might be searching for the same issue and read that Initialize is documented as optional.

**Comment by andrew-charles-callminer** [comment]
I have noticed this behavior as well.

**Comment by salarcode** [comment]
`Unknown` is the correct type for classes and objects. Both `Initialize` and Serialize method call `GetRootTypeComputed` to compute and cache the serializes and in some scenarios `Initialize` can help application speed because of pre-calculated cache. It has no other benefit and hence it is optional.

To help you better with the issue could you please provide a working model of a class the has the issue of being serialized to zero bytes?
and is this only happening in .net 6.0 ? and works fine in .net 5 or 4.8?

**Comment by mousetrap-systems** [comment]
This is going to sound silly but I can no longer reproduce this issue, despite having NO code changes in my Bois console test - it used the same `Project` class from the example in readme.md and gave me the zero-byte issue regardless of compiling from the source or direct using the Nuget package and regardless of using `FileStream` or `MemoryStream` - unfortunately I didn't test on net5.0.

There are only TWO changes to my environment, [1] My workstation has restarted overnight (often running weeks on end) and this morning [2] IDE was updated to **Microsoft Visual Studio Community 2022 (64-bit) 17.3.0 Preview 1.1**. So my test code now Serializes fine removing `Initialize`, and now I can get same result from my production code (net6.0). Must be something in my machine environment earlier this week but I'm at a loss.

If I spot it again I'll take careful notes and revisit on this thread. For what it's worth definitely wasn't dreaming this zero bytes effect - I spent about 6 hours total reworking my Archive function away from BinaryFormatter and testing Bois with a huge range of my custom objects.

Thanks again for the elegant, functional, compact design.

**Comment by salarcode** [comment]
No worries, this is indeed very strange. I'm keen to get more info if this was actually environment issue. Please let me know if this happened again.

Also please check the .net version. An upgrade might have done something. Also I have not tested Bois with .net 7 yet as with new features like AOT might cause issues and since you're running the preview of VS you might have been using the latest version by default

I'm glad that this project is helping.

**Comment by mousetrap-systems** [comment]
I'm pleased to say I've isolated the behaviour on this, can reproduce it and it's not a BOIS issue so much as it is a reflection on my own programming skills.

1. Not framework or environment dependent - reproducible on both net5.0 and net6.0
2. Not async-related
3. Nothing to do with attributes
4. IS related to the compiler (beyond my pay-grade to understand)

I had created a common library which was a one-place-serializes-all, my mistake was to pass as `object`, in the following code the size of the memory stream will always be ZERO BYTES:

    public static byte[] Serialize(object _object)
    {
        byte[] output_bytes;

        BoisSerializer bois = new BoisSerializer();

        using (MemoryStream ms = new MemoryStream())
        {
            bois.Serialize(_object, ms);
            output_bytes = ms.ToArray();
        }

        return output_bytes;
    }

... it can be fixed by changing the input parameter to **dynamic**. This produces the expected byte stream from the object targeted for serialization.

    public static byte[] Serialize(dynamic _object)
    {
        byte[] output_bytes;

        BoisSerializer bois = new BoisSerializer();

        using (MemoryStream ms = new MemoryStream())
        {
            bois.Serialize(_object, ms);
            output_bytes = ms.ToArray();
        }

        return output_bytes;
    }

I guess that makes sense; so for whatever reason using 'object' will strip it somehow of its original type identifiers - at least to the point where bois can't recognise it, whereas the 'dynamic' will send through information about the type. Anyway, now I have a kick-arse common method using BOIS and I still don't need to decorate everything with [Serialize] so this is a major win. In this project i have to serialize hundreds of thousands of objects and dozens of different POCO so bois is doing great.

**Comment by salarcode** [comment]
It makes sense now, you are calling `Serialize<T>` method which is generic and `T` is is identified as `object` which has no properties and hence the zero output.

You can either make your own method to be generic or call the overload of Serialize which takes the input and its type.
Also I advise not using `dynamic` type in here as it is slow.

Here is generic version of your method which I recommend:
```
public static byte[] Serialize<T>(T obj)
{
	byte[] output_bytes;

	BoisSerializer bois = new BoisSerializer();

	using (MemoryStream ms = new MemoryStream())
	{
		bois.Serialize(obj, ms);
		output_bytes = ms.ToArray();
	}

	return output_bytes;
}
```
And FYI this is `object` version:
```
public static byte[] Serialize(object obj)
{
	byte[] output_bytes;

	BoisSerializer bois = new BoisSerializer();

	using (MemoryStream ms = new MemoryStream())
	{
		bois.Serialize(obj, obj.GetType(), ms);
		output_bytes = ms.ToArray();
	}

	return output_bytes;
}
```

If your app is not a web application, I recommend using a static version of serializer which benefit from cache.
The final version for you:
```
private static readonly BoisSerializer _bois = new BoisSerializer();
public static byte[] Serialize<T>(T obj)
{
	using (var ms = new MemoryStream())
	{
		_bois.Serialize(obj, ms);
		return ms.ToArray();
	}
}
```

**Comment by mousetrap-systems** [comment]
That's great code guidance. Thanks for the assist!
