### ISSUE TITLE
Deserialization error "Unable to read beyond the end of the stream"

### ISSUE THREAD

**Issue by d-vyd** [salarcode/Bois#26]
Hi. I'm using Bois on a new project and am seeing the error `System.IO.EndOfStreamException
  HResult=0x80070026 Message=Unable to read beyond the end of the stream. Source=System.Private.CoreLib` on the last line (deserialize). My classes are all simple with a parameterless constructor. What am I doing wrong?

```
        public static void Main()
        {
            Agent john = Agent.Create(0, "John");
            Agent sarah = Agent.Create(1, "Sarah");
            var r1 = Relationship.Create(1, RelationshipKind.SiblingOf, 5);
            var r2 = Relationship.Create(0, RelationshipKind.SiblingOf, 3);
            john.Relations.Add(r1);
            sarah.Relations.Add(r2);

            BoisSerializer.Initialize<Agent>();
            var boisSerializer = new BoisSerializer();

            var mem = new MemoryStream();
            boisSerializer.Serialize(john, mem);
        
            Agent john2 = boisSerializer.Deserialize<Agent>(mem);

        }
```

**Comment by Dypso** [comment]
Hello, just after serialization, you need to get back at the beginning of the memory stream (ie. position at 0).

**Comment by d-vyd** [comment]
Thanks! I noticed that a few of my lists are not ILISTs, which may also be causing (or will cause) trouble.

**Comment by Dypso** [comment]
Not sure : the message you have is clearly because when you call the deserialize method, it will try to read after the end of the memory stream position. If you rewind it at the beggining , it should work

**Comment by d-vyd** [comment]
Yes, `mem.Position = 0;` solved the issue. Thank you!
