### ISSUE TITLE
Out of memory error when serializing a Dictionary with 16 million items

### ISSUE THREAD

**Issue by zanek** [salarcode/Bois#28]
I'm getting a Out of memory error when serializing a Dictionary with 16 million items.

I'm using .Net Core 6.0  on Windows with 128GB of RAM. The total size before I serialize the dictionary is 18GB.
Any idea why the PICKLE() method is running out of memory? gcLargeObjects is allowed by default with .Net core

**Comment by salarcode** [comment]
Pickle is only working on memory buffer and can't work with files, so for that large data it makes sense to run out of memory.
Unfortunately there is no workaround this.

**Comment by salarcode** [comment]
Pickle is only working on memory buffer and can't work with files, so for that large data it makes sense to run out of memory.
For this use of File Streams is needed which `BoisLz4Serializer` doesn't support currently

**Comment by salarcode** [comment]
Tracking this with #29
