### ISSUE TITLE
Support for dotnet 6+ DateOnly & TimeOnly

### ISSUE THREAD

**Issue by rudzen** [salarcode/Bois#32]
For `NET6_0_OR_GREATER` the types

- `DateOnly`
- `DateOnly?`
- `TimeOnly`
- `TimeOnly?`

Is currently not supported, would be great with added support for these types. Doesn't look too complex to add them in the existing codebase since they are both representable through an `int`.

**Comment by salarcode** [comment]
This is being released with next version
