### ISSUE TITLE
EndOfStream exception is thrown, when de-serializing a zero-length byte array from a MemoryStream when TryGetBuffer() returns false

### ISSUE THREAD

**Issue by phisch84** [salarcode/Bois#33]
Scenario:
.) An object with a byte-array field, which is initialized to zero (field = new byte[0]) is serialized into a MemoryStream (ms) using the Serialize() method.
.) The data of this stream are then further packet into another byte array for data transfer (byte[] dta = ms.ToArray())
.) The data transfer array is later deserialized, by putting it back into a stream (var new_ms = new MemoryStream(dta)).
.) This stream is then deserialized using Deserialize(new_ms, target_type) - where target_type = e.g. myObjectOfClass.GetType()

Error:
The given scenario fails because of a EndOfStream thrown in PrimitiveReader.ReadByteArray(BufferReaderBase)

Potential fix in PrimitiveReader.ReadByteArray(BufferReaderBase):
return new byte[0] if length == 0.

Remark:
Most likely that should be fixed in https://github.com/salarcode/BinaryBuffers at the reader itself.

**Comment by salarcode** [comment]
Fixed with #34
