### ISSUE TITLE
Deserialization error

### ISSUE THREAD

**Issue by sunilpraktan** [salarcode/Bois#4]
Hi,
Serialization working but it shows "Non-negative number required. Parameter name: count" error while de-serialization. in different project same function works great. kindly suggest.

Thanks in Advance
Sunil

**Comment by salarcode** [comment]
Can you provide the sample class that has the error? In which platform you are working(portable, .net 4...)?

**Comment by sunilpraktan** [comment]
we are working on .net framework 4.6. it is 3 tire architecture Application. WCF service project serialize it well. but at client project de-serialization failed. the strange part is that, if i create new client WPF windows application and consume same wcf service then it de-serialize without any issue.
please help as it is really nice serializer for LOB app.
i don't know weather i explain perfectly or not but things are like this.

**Comment by salarcode** [comment]
Without a working sample model class or project I cannot test the faulty behavior, thus I cannot fix it.

**Comment by sunilpraktan** [comment]
Hi,
Sorry for delayed response, as i was on business tour.
we can do one thing that i will give access to my PC through TeamViewer or
any thing as per your convinience if possible.
my project on .net 4.6.1 platform. WPF,WCF based ERP system.
your help is appreciable.

my official mail id is sunil@praktan.com and skype id is : sunil.praktan

Thanks

Sunil

On Sat, Feb 27, 2016 at 12:25 AM, Salar Khalilzadeh <
notifications@github.com> wrote:

> Can you provide the sample class that has the error? In which platform you
> are working(portable, .net 4...)?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/salarcode/Bois/issues/4#issuecomment-189422560.

## 

_Thank You_

_SUNIL J PATIL_

_Praktan Technologies_

_2,Union bank Colony,Rajeev Nagar,_

_Indira Nagar,Nashik-422009_

_Mobile: (+91) 9422 944 380 (Nashik)_

_SKYPE ID : sunil.praktan_

_web: *_www.praktan.com* http://www.praktan.com/

**Comment by salarcode** [comment]
No, just a sample class that has the problem is enough.

**Comment by sunilpraktan** [comment]
Thanks a Million for your great help.

On Thu, May 5, 2016 at 1:54 PM, Salar Khalilzadeh notifications@github.com
wrote:

> Closed #4 https://github.com/salarcode/Bois/issues/4.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/salarcode/Bois/issues/4#event-651198370

## 

_Thank You_

_SUNIL J PATIL_

_Praktan Technologies_

_2,Union bank Colony,Rajeev Nagar,_

_Indira Nagar,Nashik-422009_

_Mobile: (+91) 9422 944 380 (Nashik)_

_SKYPE ID : sunil.praktan_

_web: *_www.praktan.com* http://www.praktan.com/
