### ISSUE TITLE
Serialize private setter.

### ISSUE THREAD

**Issue by gohsianghwee** [salarcode/Bois#5]
Hi,

I have a class with Private Setter, when I tried to serialize it, it threw me "Value cannot be null" exceptions. Is there anyway to serialize and deserialize private setter. I tried BinaryFormatter and it works but the performance is less than ideal. Thanks.

The sample class is as below.

  public class PrivateSetPropertyEmployee
    {
        public PrivateSetPropertyEmployee()
        {

```
    }

    public PrivateSetPropertyEmployee(string name, int age)
    {
        this.Name = name;
        this.Age = age;
    }

    public string Name { private set; get; }

    public int Age { get; private set; }
}
```

**Comment by salarcode** [comment]
Thank you for the report, the issue is fixed and the fix will be available in the next release.

**Comment by gohsianghwee** [comment]
Thanks. I shall try it out again.

**Comment by salarcode** [comment]
A new version for this bug is released.
