### ISSUE TITLE
Object containment and null issues

### ISSUE THREAD

**Issue by padmanabhak** [salarcode/Bois#6]
private object ReadMember(BinaryReader reader, BoisMemberInfo memInfo, Type memType)
        {
            if (memInfo.IsNullable &&
                !memInfo.IsSupportedPrimitive &&
                (!memInfo.IsContainerObject || memInfo.IsStruct))
            {
                bool isNull = reader.ReadByte() != 0;

```
            if (isNull)
            {
                return null;
            }
        }
```

For the  pseudo-code below, the classContained in ClassA is null. However, when we deserialize we get an object for ClassContained. Is this by design?

This causes issues, when we have nested contained classes, becuase of the above code.

classA 
{
         classContained obj;
}

classContained
{
}

main()
{
       classA obj = new ClassA();
        bois.Serialize(obj);

```
    deserialobj = bois.Deserialize() ;
```

}

**Comment by salarcode** [comment]
I ran your sample code and the obj is still null for me. If what you said happens, it is not by design.

**Comment by salarcode** [comment]
Do you still have the issue? If so, can you please provide another example of the issues?
